// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1lsjscnJClxTGp6kmtk4bxRQvpn3kDDM',
    appId: '1:1059993649749:android:07ccb1a40bca509e6b8adc',
    messagingSenderId: '1059993649749',
    projectId: 'skyry-39c85',
    databaseURL: 'https://skyry-39c85.firebaseio.com',
    storageBucket: 'skyry-39c85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLMS4K_1xI787RiqULwgw9RSmJhJSp2HM',
    appId: '1:1059993649749:ios:5a146caa99b63bad6b8adc',
    messagingSenderId: '1059993649749',
    projectId: 'skyry-39c85',
    databaseURL: 'https://skyry-39c85.firebaseio.com',
    storageBucket: 'skyry-39c85.appspot.com',
    iosClientId: '1059993649749-o4jggnhpu0hfucrsrq2a70uqa2rdlb8s.apps.googleusercontent.com',
    iosBundleId: 'com.firstapporg.mynotes',
  );
}
